#!/usr/bin/env python
"""igcommit - InnoGames Commit Validation Script

This the pre-receive script for Git repositories to validate pushed commits
on the server side.

Copyright (c) 2016, InnoGames GmbH
"""

from igcommit import commit_checks, file_checks
from igcommit.commit_list import CommitList
from igcommit.utils import iter_buffer


failed = False
commits = CommitList.read_from_input()
checks = []

# Commit checks
checks.append(commit_checks.CheckDuplicateCommitSummaries())
checks.append(commit_checks.CheckMisleadingMergeCommit())
checks.append(commit_checks.CheckCommitMessage())
checks.append(commit_checks.CheckCommitSummary())
checks.append(commit_checks.CheckCommitTags())
checks.append(commit_checks.CheckChangedFilePaths())

# File meta checks
checks.append(file_checks.CheckExecutable())

# Puppet
checks.append(file_checks.CheckCommand(
    [
        'puppet',
        'parser',
        'validate',
        '--color=false',
        '--confdir=/tmp',
        '--vardir=/tmp',
    ],
    extension='pp',
))
checks.append(file_checks.CheckCommand(
    [
        'puppet-lint',
        '--fail-on-warnings',
        '--no-autoloader_layout-check',
        '/dev/stdin',
    ],
    extension='pp',
))

# Python
flake8_check = file_checks.CheckCommandWithConfig(
    ['flake8', '-'],
    extension='py',
    config_name='.flake8',
    config_optional=True,
)
checks.append(flake8_check)
checks.append(file_checks.CheckCommand(
    ['pycodestyle', '-'],
    extension='py',
    preferred_checks=[flake8_check],
))
checks.append(file_checks.CheckCommand(
    ['pyflakes'],
    extension='py',
    preferred_checks=[flake8_check],
))

# Ruby
checks.append(file_checks.CheckCommand(
    ['rubocop', '--format=emacs', '--stdin', '/dev/stdin'],
    extension='rb',
))

# Shell
checks.append(file_checks.CheckCommand(
    ['shellcheck', '--format=gcc', '/dev/stdin'],
    extension='sh',
))

# JavaScript
checks.append(file_checks.CheckCommandWithConfig(
    ['jscs', '--max-errors=-1', '--reporter=unix'],
    extension='js',
    config_name='.jscs.json',
))

# We are buffering the checks to let them run parallel in the background.
# Parallelization only applies to the CheckCommands.  It has no overhead,
# because we have to run those commands the same way externally, anyway.
# We only have a limit in there to avoid hitting OS's process limit.
for check in iter_buffer(commits.expand_checks_all(checks), 32):
    check.print_problems()
    failed |= check.failed

if failed:
    raise SystemExit('Checks failed')
