#!/usr/bin/env python
# coding: utf-8
"""igcommit - The Git pre-receive hook to validate commits

Copyright (c) 2016, InnoGames GmbH
"""

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

from igcommit.prereceive import main

sys.exit(main())
